on: 
  workflow_dispatch:  
    inputs:
      environment:
        description: 'Define env name'     
        required: true
        default: 'prod'
        type: choice
        options:
        - lab
        - dev
        - test
        - prod
  push:
    branches: ['main']
    paths:
    - 'infrastructure/**'
    
env:
  target_env: 'lab'

    
name: Azure Infrastructure
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    name: 'Infrastructure deploy'
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Set target if manual 
      run: |
        if [[ $GITHUB_EVENT_NAME != 'push' ]]; then
            echo "target_env=${{inputs.environment}}" >> "$GITHUB_ENV"      
        fi
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
        enable-AzPSSession: true

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1.0.9
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: '${{ secrets.AZURE_RG }}-${{ env.target_env }}'
        template: ./infrastructure/main.bicep
        deploymentName: 'Infrastructure_deploy_${{ steps.date.outputs.date }}'
        parameters: 'location=westeurope environment=${{ env.target_env }}'
        failOnStdErr: false
